/**
 * @author gps on 29-08-2020 at 08:08
 */
package employee;


import model.EmpDetails;

import javax.swing.*;

public class ChangePwd {
    public class ChangePwd extends javax.swing.JFrame {
/**
 * Creates new form ChangePwd
 */

EmpDetails ed;
        public ChangePwd(EmpDetails ed) {
            this.ed=ed;
            initComponents();
            /**
             * This method is called from within the constructor to initialize the form.
             * WARNING: Do NOT modify this code. The content of this method is always
             * regenerated by the Form Editor.
             */
            @SuppressWarnings("unchecked")
            // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
            // Generated using JFormDesigner Evaluation license - unknown
            private void initComponents() {
                jLabel1 = new JLabel();


        }



        }



    }


}
